### ISSUE TITLE
How can i use these variables via bash scripts

### ISSUE THREAD

**Issue by okyou** [nksft/graylog2-plugin-exec#1]
how can i use these variables via bash scripts? it seems ${stream.title} not work,could you plz show me a example how to use it,thanks

**Comment by nksft** [comment]
There is no template like support yet, but you can send any parameters statically in the script field and catch it in your bash script as $1, $2 and...

**Comment by okyou** [comment]
semms can not exposing the alarm details as env variables.for example,when i use bash /opt/graylog-1.3.4/bin/callbacks/test.sh stream.title ,it did not work.

**Comment by nksft** [comment]
Yes, you can't send variables. Just the values. For example: "bash /opt/graylog-1.3.4/bin/callbacks/test.sh FAILED_LOGINS".

**Comment by dmitriy-shleht** [comment]
Why does my script is not called?
![screan](https://cloud.githubusercontent.com/assets/13961834/18786152/17b79f32-81a5-11e6-86af-8d1c85014416.PNG)

```
#!/bin/bash
echo $@ >> log.txt 
```

**Comment by nksft** [comment]
Whats your Graylog version?

**Comment by dmitriy-shleht** [comment]
Graylog version 2.1

**Comment by nksft** [comment]
It seems it's not working with this version! Maybe if I find the problem I will release an update.

**Comment by dmitriy-shleht** [comment]
**Thank you. I would really wait for your updates!**

**Comment by nksft** [comment]
@work-des 
It seems it was just a permission problem. You have to set the appropriate permissions (scripts and folders) for the graylog.
This works for me:
bash /tmp/test.sh dmitrly

test.sh:
#!/bin/bash
echo $@ >> /tmp/log.txt
