### ISSUE TITLE
alert is being triggered but script not running

### ISSUE THREAD

**Issue by ovadm** [nksft/graylog2-plugin-exec#3]
Hello,

I set permissions for user graylog to all path and verified that it can execute the script from cli, I even set graylog gid to zero but it didn't help - script still not being executed.

Is there any log file that I can look for the problem

Thanks
Ovad

**Comment by nksft** [comment]
Hi Ovad,

Just for testing you can touch a file in /tmp folder (touch /tmp/test) or put your script in /tmp folder and **make it executable**.
My test script is:
`#!/bin/bash`
`echo "Test Script $@" >> /tmp/test.log`

and in my plugin config:
(/tmp/test.sh input1)

**Comment by ovadm** [comment]
Hi,

I already tried this with no success.
I am able to run other java classes with no issue
Java version is 7
Graylog usermod set with group 0

Thanks,
Ovad

**Comment by ovadm** [comment]
Also with  command lsof | grep execommand-alarmcallback-1.0.0.jar I can see that the file opens many times

From: Ovadia Mani
Sent: Thursday, February 23, 2017 4:16 PM
To: 'nksft/graylog2-plugin-exec' <reply@reply.github.com>; nksft/graylog2-plugin-exec <graylog2-plugin-exec@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [nksft/graylog2-plugin-exec] alert is being triggered but script not running (#3)

Hi,

I already tried this with no success.
I am able to run other java classes with no issue
Java version is 7
Graylog usermod set with group 0

Thanks,
Ovad

**Comment by ovadm** [comment]
btw though the jar file opens, I couldn't find any of the classes inside running

**Comment by nksft** [comment]
Oracle Java SE 8 or later is in the [Graylog 2 requirements](http://docs.graylog.org/en/2.2/pages/installation.html#system-requirements). Maybe this will help to solve your problem.

**Comment by ovadm** [comment]
No, same result.

**Comment by ovadm** [comment]
Solved following  gl upgrade to  2.2.1
Not sure why
thanks

**Comment by nksft** [comment]
Glad to hear it. What was your gl version?

**Comment by ovadm** [comment]
2.1.2
